version: "3"
services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}
    build: .
    environment:
      - ERRONKA_API_BASE_URL=${ERRONKA_API_BASE_URL}
      - ERRONKA_API_URL=${ERRONKA_API_URL}
    depends_on:
      - db
      - php_api
    ports:
      - "${WEB_PORT}:8069"
      - "${WEBSOCKET_PORT}:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"
  php_api:
    image: php:8.2-apache
    command: bash -c "docker-php-ext-install pdo_mysql && apache2-foreground"
    volumes:
      - ../WEB-API-ODOO-CONNECT:/var/www/html
    ports:
      - "8090:80"
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-db-data:
  odoo-web-data:
